language: python
python: 2.7

env:
  matrix:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=py26-tw140
    - TOX_ENV=py27-tw140
    - TOX_ENV=pypy-tw140
    - TOX_ENV=py26-tw132
    - TOX_ENV=py27-tw132
    - TOX_ENV=pypy-tw132
    - TOX_ENV=py26-tw131
    - TOX_ENV=py27-tw131
    - TOX_ENV=pypy-tw131
    - TOX_ENV=py26-tw130
    - TOX_ENV=py27-tw130
    - TOX_ENV=pypy-tw130
    - TOX_ENV=py26-tw123
    - TOX_ENV=py27-tw123
    - TOX_ENV=pypy-tw123
    - TOX_ENV=py26-tw122
    - TOX_ENV=py27-tw122
    - TOX_ENV=pypy-tw122
    - TOX_ENV=py26-tw121
    - TOX_ENV=py27-tw121
    - TOX_ENV=pypy-tw121
    - TOX_ENV=pyflakes

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pyflakes

script: pip install tox && tox -e $TOX_ENV

notifications:
    email: false
