language: python
python:
    - 2.7
    - "pypy-5.6.0"

env:
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw162
    - TOX_ENV=py27-tw160
    - TOX_ENV=py27-tw150
    - TOX_ENV=py27-tw140
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pypy-tw162
    - TOX_ENV=pypy-tw160
    - TOX_ENV=pypy-tw150
    - TOX_ENV=pypy-tw140
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
#  allow_failures:
#    - env: TOX_ENV=pyflakes

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
