language: python

# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
  - master

python:
  - 2.7
  - 3.5

env:
  - python: 2.7
  - TOX_ENV=py27-test-twlatest
  - python: 2.7
  - TOX_ENV=py27-test-twtrunk
  - python: 3.5
  - TOX_ENV=py35-ported
  - python: 3.5
  - TOX_ENV=py35-test-twtrunk
  - python: 2.7
    TOX_ENV=linters

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py35-test-twtrunk

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_script:
  - codecov

notifications:
    email: false
