language: python

# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOX_ENV=py27-test-twlatest
  - python: 2.7
    env: TOX_ENV=py27-test-twtrunk
  - python: 3.5
    env: TOX_ENV=py35-ported
  - python: 3.5
    env: TOX_ENV=py35-test-twtrunk
  - python: 3.6
    env: TOX_ENV=py36-ported
  - python: 3.6
    env: TOX_ENV=py36-test-twtrunk
  - python: 3.7
    env: TOX_ENV=py37-ported
  - python: 3.7
    env: TOX_ENV=py37-test-twtrunk
  - python: 2.7
    env: TOX_ENV=linters
  - python: 3.7
    env: TOX_ENV=linters
  allow_failures:
    - env: TOX_ENV=py35-test-twtrunk
    - env: TOX_ENV=py36-test-twtrunk
    - env: TOX_ENV=py37-test-twtrunk

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_script:
  - codecov

notifications:
    email: false
